apiVersion: apps/v1
kind: Deployment
metadata:
  name: githubactions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: githubactions
  template:
    metadata:
      labels:
        app: githubactions
    spec:
      containers:
        - name: githubactions
          image: gcr.io/fcbhealthreaktor/githubactions:#{buildid}#
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 256m
              memory: 512Mi
            requests:
              cpu: 256m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /
              port: 80
            successThreshold: 1
            failureThreshold: 5
            initialDelaySeconds: 15
            timeoutSeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            successThreshold: 1
            failureThreshold: 5
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5             
---
apiVersion: v1
kind: Service
metadata:
  name: githubactions
spec:
  type: NodePort
  selector:
    app: githubactions
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
